info:
  contact: {}
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Users
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Take refresh token and produce 2 new tokens
      produces:
      - application/json
      responses:
        "400":
          description: Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get new tokens
      tags:
      - Users
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided email and password.
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
            username:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid credentials / User already exists
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Users
  /api/auth/user-info:
    get:
      consumes:
      - application/json
      description: Take access token from header  and provide user info
      produces:
      - application/json
      responses:
        "400":
          description: Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user info
      tags:
      - Users
  /api/cart:
    get:
      consumes:
      - application/json
      description: Retrieves the shopping cart for a specific user using the access
        token stored in cookies.
      parameters:
      - description: Access Token
        in: header
        name: access_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"uid": "string", "userCart": "object"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"error": "string"}'
          schema:
            additionalProperties: true
            type: object
      summary: Get user cart
      tags:
      - cart
  /api/cart/items:
    post:
      consumes:
      - application/json
      description: Adds a product to the user's shopping cart using the access token
        stored in cookies.
      parameters:
      - description: Access Token
        in: header
        name: access_token
        required: true
        type: string
      - description: Product ID and Quantity
        in: body
        name: input
        required: true
        schema:
          properties:
            product_id:
              type: integer
            quantity:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Product successfully added to cart"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"error": "string"}'
          schema:
            additionalProperties: true
            type: object
      summary: Add item to cart
      tags:
      - cart
  /api/products:
    get:
      description: Retrieves a list of all available products.
      produces:
      - application/json
      responses:
        "200":
          description: List of products retrieved successfully
          schema:
            items:
              properties:
                ID:
                  type: integer
                description:
                  type: string
                image:
                  type: string
                name:
                  type: string
                price:
                  type: integer
                slug:
                  type: string
              type: object
            type: array
        "400":
          description: Products not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Creates a new product with the provided information.
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          properties:
            description:
              type: string
            image:
              type: string
            name:
              type: string
            price:
              type: integer
            slug:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Product created successfully
          schema:
            properties:
              ID:
                type: integer
              description:
                type: string
              image:
                type: string
              name:
                type: string
              price:
                type: integer
              slug:
                type: string
            type: object
        "400":
          description: Invalid product data / Cannot create product
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new product
      tags:
      - Products
  /api/users:
    get:
      consumes:
      - application/json
      description: Provide users info
      produces:
      - application/json
      responses:
        "400":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get users info
      tags:
      - Users
swagger: "2.0"
